### ISSUE TITLE
DES - Responsive screens

### ISSUE THREAD

**Issue by monica-pen** [MentallyFriendly/ensi#101]
**Tablet**
- [ ] Home
- [ ] Our Services (Overview)
- [ ] Our Services (Detail) x4
- [ ] Our People
- [ ] Our Story
- [ ] Contact

**Mobile**
- [ ] Home
- [ ] Our Services (Overview)
- [ ] Our Services (Detail) x4
- [ ] Our People
- [ ] Our Story
- [ ] Contact

**Comment by jomentallyfriendly** [comment]
@monica-pen is this ticket up to date?

**Comment by monica-pen** [comment]
@jomentallyfriendly we're doing this on the fly in Webflow. So I can only review/do when Sasha isn't logged in.
