### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#104]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet

**Comment by smypf** [comment]
@monica-pen Need help on this.

**Comment by jomentallyfriendly** [comment]
@smypf here are the logos ENS wants to integrate into the slider. @monica-pen it might be worth checking them and creating assets Sasha can implement.

**Comment by smypf** [comment]
They've been added.

**Comment by smypf** [comment]
Responsiveness has been added. Need to talk to @monica-pen about the arrows for the sliders and how we're going to fit them in.

**Comment by smypf** [comment]
Sliders have been implemented.

**Comment by jomentallyfriendly** [comment]
QA passed.
