### ISSUE TITLE
Our People Listing Page

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#105]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet
- [x] Accordion

**Comment by smypf** [comment]
This can be seen at http://ens-base-template.webflow.io/our-people

**Comment by smypf** [comment]
@monica-pen Please check responsive views

**Comment by jomentallyfriendly** [comment]
@smypf can you please add the correct image for the map and the correct figures? All defined in InVision right @monica-pen?

**Comment by smypf** [comment]
@jomentallyfriendly Map has been added. Markers and figures have been checked against the designs.

**Comment by jomentallyfriendly** [comment]
QA passed.
