### ISSUE TITLE
Our People Detail Page

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#106]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet
- [x] other practitioners

**Comment by smypf** [comment]
@jomentallyfriendly I'm blocked by WebFlow. Basically the filtering of other practitioners is limited to a set value. I haven't found a way to set it to a value based on the collection item. I've reached out to WebFlow support to see if it's possible. **Moved to blocked for this reason.**

@monica-pen Can you please have a look at the responsive layout and make sure that you're happy. This one is pretty basic so I don't think that you'll have any problems. You might want to move the image position and I'm not fussed if that's the case.

**Comment by jomentallyfriendly** [comment]
@smypf so what do you suggest we do if it's not possible? Manual collections? Did you look into if collections cost extra?

**Comment by smypf** [comment]
$10 per month.

IMO it's worth it because it'll make managing their users easier. I've tested and you're able to copy a site and the collections are copied over as well.

I've got an idea for if WebFlow come back and tell us that it's not possible. JS will check which region we're in and hide the inappropriate regions.

**Comment by jomentallyfriendly** [comment]
Ok. Let's discuss this with ENSI in today's Check In

**Comment by jomentallyfriendly** [comment]
@smypf detail pages looks good.
@monica-pen I would say the profile should be under the name on mobile? Thoughts?

**Comment by smypf** [comment]
@jomentallyfriendly @monica-pen Sorry, I don't understand what needs to change.

**Comment by jomentallyfriendly** [comment]
@sasha nothing really if the filtering of other practitioners works.

**Comment by smypf** [comment]
Ok, Other Practitioners now works. There's a period where they're all not visible and then one of them gets shown, but I believe that this is an acceptable workaround for this.

**Comment by jomentallyfriendly** [comment]
QA passed.
