### ISSUE TITLE
Better Outcomes / Conversational flow page

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#107]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet

**Comment by smypf** [comment]
@monica-pen can you please check out http://ens-base-template.webflow.io/let-us-help-you and see if you're happy with the responsive layout that I've put together.

**Comment by jomentallyfriendly** [comment]
QA Failed.

![screen shot 2016-11-14 at 3 59 23 pm](https://cloud.githubusercontent.com/assets/18299131/20253885/70810778-aa83-11e6-8852-acba6f9c97eb.png)

**Comment by smypf** [comment]
@jomentallyfriendly I think I've fixed that. Check it out now.

**Comment by smypf** [comment]
@monica-pen Please check responsive views

**Comment by jomentallyfriendly** [comment]
QA passed.
