### ISSUE TITLE
Generic Content Page

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#108]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet

- [x] Our Story Page

**Comment by smypf** [comment]
http://ens-base-template.webflow.io/our-story

**Comment by jomentallyfriendly** [comment]
@smypf 
Can we have a Youtube in there to demonstrate that this works? Please use https://www.youtube.com/watch?v=uRvudffeBmE

**Comment by smypf** [comment]
@jomentallyfriendly This has been added.

**Comment by smypf** [comment]
@monica-pen Please check responsive view.

**Comment by jomentallyfriendly** [comment]
QA approved.
