### ISSUE TITLE
Language Selector

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#111]
- [x] Dropdown with other languages
- [x] Responsive

**Comment by smypf** [comment]
This can be seen at http://ens-base-template.webflow.io/

**Comment by jomentallyfriendly** [comment]
How does ENS add more languages in the future or add links to the current languages?

**Comment by jomentallyfriendly** [comment]
@monica-pen did you check the selector across viewports and can approve it's working as it should?

**Comment by smypf** [comment]
@jomentallyfriendly Copy paste. The styles will do it all themselves.

**Comment by smypf** [comment]
@smypf Languages don't show in tablet viewport.

**Comment by smypf** [comment]
Fixed.

**Comment by jomentallyfriendly** [comment]
QA passed. @smypf what if we launch with less languages than currently implemented? Is the selector editable?

**Comment by smypf** [comment]
100% editable. And I've found where the "template" functionality is this will be updated automatically across all pages.

**Comment by jomentallyfriendly** [comment]
Nice!
