### ISSUE TITLE
Our services

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#112]
- [x] Layout implemented
- [x] mobile
- [x] mobile landscape
- [x] tablet

**Comment by jomentallyfriendly** [comment]
@monica-pen are the illustrations placed right in mobile views? Seems like they should be under each headline to have meaning. Thoughts?

![screen shot 2016-11-15 at 2 27 10 pm](https://cloud.githubusercontent.com/assets/18299131/20292193/c29eb5de-ab3f-11e6-8740-8786f047401f.png)

The illustration is too small for the size of the viewport as well. Can you please fix that @smypf?
![screen shot 2016-11-15 at 2 26 41 pm](https://cloud.githubusercontent.com/assets/18299131/20292199/cbcd2b04-ab3f-11e6-977a-2b61c95fac95.png)

**Comment by smypf** [comment]
Footer has been fixed.

**Comment by jomentallyfriendly** [comment]
QA passed.
