### ISSUE TITLE
Header & Footer

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#114]
@smypf 
Please link the icons.
https://twitter.com/ensinter
https://www.linkedin.com/company/ens-international

@smypf 
Please create T&Cs and PP with content from here and link up the footer.
http://www.negotiate.org/privacy-policy.html
http://www.negotiate.org/terms-conditions.html

@monica-pen did you design states for these elements?

@smypf 
Language selector is hard to use as it disappears if you don't move the mouse over the little gap fast. How will this work in the extreme state of having no other languages available?

![screen shot 2016-11-15 at 2 21 56 pm](https://cloud.githubusercontent.com/assets/18299131/20292124/20fda06e-ab3f-11e6-864e-26ca99b16b18.png)

@smypf please rename 'Our People' to 'Our Practitioners'

**Comment by smypf** [comment]
Social links and privacy policies have been created.

I'll fix the issue with the rollover.

**Comment by smypf** [comment]
I've fixed the issue with the rollover.

**Comment by jomentallyfriendly** [comment]
QA passed for rollover.
@sasha Can you please make nav font size 18px instead of 16px.

**Comment by smypf** [comment]
This has been done as part of #129
