### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#115]
The buttons are not all styled properly I think. Chrome OSX latest. Copy seems a little off.

![screen shot 2016-11-15 at 2 36 31 pm](https://cloud.githubusercontent.com/assets/18299131/20292341/f13b5400-ab40-11e6-9154-4643959362a3.png)

**Comment by smypf** [comment]
@jomentallyfriendly @monica-pen Please check this to ensure that you're happy. I've adjusted slightly.

**Comment by jomentallyfriendly** [comment]
QA passed.
