### ISSUE TITLE
Sasha to investigate PDF downloads in Webflow

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#123]

**Comment by smypf** [comment]
WebFlow does not support non-image file uploads. We will need to approach in some other manner.

Is this something that we were required to do?

**Comment by jomentallyfriendly** [comment]
There is a PDF download on one courses page. Needs to be hosted via Dropbox or Google Drive.

**Comment by jomentallyfriendly** [comment]
Webflow does not support this. Need to use Dropbox or Google Drive for this.
https://help.webflow.com/article/can-i-have-downloadable-files-on-my-site
