### ISSUE TITLE
Contact Us field focus

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#136]
Minor error with focused field.

![screen shot 2016-11-22 at 11 42 18 am](https://cloud.githubusercontent.com/assets/18299131/20506521/cfd3b970-b0a8-11e6-87e4-561d1df0ea3c.png)

**Comment by smypf** [comment]
A change has been applied for this.

This means that there is a double up of the borders.

**Comment by jomentallyfriendly** [comment]
sheberoit thanks!
