### ISSUE TITLE
Setting up multiple languages in Webflow

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#137]
going with the negotiate.org/de option

**Comment by smypf** [comment]
I'm waiting for illustrations to be completed before this is done. Otherwise we'll need to add the images to all places multiple times, which will get old quick.

Moving to blocked for this reason.

**Comment by jomentallyfriendly** [comment]
We are not setting this up as ENSI will get a video how-to as per #177
