### ISSUE TITLE
Remove completed % from typeforms.

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#140]

**Comment by smypf** [comment]
I've removed the completed % from the forms.

**Comment by jomentallyfriendly** [comment]
Did you remove from the final flows? Are all final flows integrated into
1. Webflow
2. Zapier > Salesforce (Testing)

**Comment by smypf** [comment]
Can confirm that the progress meters have been removed from the final
versions of the forms.

**Comment by smypf** [comment]
This has been done.
