### ISSUE TITLE
Add default button stylings.

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#141]

**Comment by smypf** [comment]
@jomentallyfriendly Due to limitations of the Webflow system I'm not able to complete this functionality. The system treats a button as a link meaning that any styling added to the button will be applied to all links on the page.

Due to this the work around is to add a "button" class to buttons. This will add the appropriate stylings.

**Comment by jomentallyfriendly** [comment]
Fine. We just need to tell them that. You said you gonna make this happen initially but now found it does not work so not an issue. Just let them know.

**Comment by jomentallyfriendly** [comment]
This has been explained to ENSI in the check in.
