### ISSUE TITLE
ENS Content - Logos might not be great for home page testimonials

### ISSUE THREAD

**Issue by smypf** [MentallyFriendly/ensi#155]
I've had to pull the images by screen shotting them for NSW Gov Health South Western Sydney and RES Med.

Please ensure that these are correct.

**Comment by smypf** [comment]
Also - The previous NSW health looked better without the blue background.

ResMed is too tall.

**Comment by jomentallyfriendly** [comment]
This is now ENSIs responsibility as we had the training session with them.
