### ISSUE TITLE
Homepage - Animation

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#162]
- ENSI decided to use a fade-in, fade-out animation for the illustration on the homepage
- ENSI decided to finish the animation on the homepage with a 'near-handshake' and distance between male and female  as illustrated in the Check-In

Blocked by @CorcoranEd on #134.

**Comment by CorcoranEd** [comment]
[homepage-svgs.zip](https://github.com/MentallyFriendly/ensi/files/623376/homepage-svgs.zip)

**Comment by CorcoranEd** [comment]
@jo :)

**Comment by CorcoranEd** [comment]
@jomentallyfriendly :)

**Comment by smypf** [comment]
This has been added to the home page. Hopefully the like it.

**Comment by jomentallyfriendly** [comment]
Feedback from Chris

Homepage
Figures in the animation seem too small
Let’s align the top of the figures with the top of ‘Looking to’
