### ISSUE TITLE
Alignment & Spacing

### ISSUE THREAD

**Issue by jomentallyfriendly** [MentallyFriendly/ensi#179]
**From Chris**

- [x] Our Services
- Reduce a line or 2 of white space between first paragraph and next text block with image
 
- [x] Organizational Transformation
- Let’s make the image a bit smaller and have some more space between it and the text
 
- [x] Negotiation Advice
- Let’s move the image up in line with the text
 
- [x] In-House Teams
- Let’s move the image up in line with the text
 
- [x] Open Courses
- Let’s move the image up in line with the text, and make it a bit smaller

- [x] Our Story
- Increase breaks between paragraphs
- Left align image and video

- [x] Language Selector
- @monica-pen please upload the AI file with all flags
- @smypf please add flags to Webflow but redirect to the same content as there will be no difference. Is that possible?

**Comment by monica-pen** [comment]
[Flags of World.eps.zip](https://github.com/MentallyFriendly/ensi/files/659917/Flags.of.World.eps.zip)

**Comment by jomentallyfriendly** [comment]
o   Homepage

§  Figures in the animation are too small

§  Let’s align the top of the figures with the top of  the ‘Looking to’ text

§  Figures appear at different times to the text i.e. the second image fadeout leaves an almost blank page which interrupts the flow of information on the page.

![image001 1](https://cloud.githubusercontent.com/assets/18299131/21754904/9428d52e-d65d-11e6-8e02-d0e55531def4.png)

o   Our Services

=C2=A7  Reduce the space between =E2=80=98What are your needs?=E2=80=99 par=
agraph and the =E2=80=98Strategic Collaboration=E2=80=99 headline

=C2=A7  Reduce the width of white space between the paragraph and the first=
 image (again, should be standard across all images on the site).


o   Organizational Transformation

=C2=A7  Let=E2=80=99s make the image a bit smaller and have some more space=
 between it and the text


o   Negotiation Advice

=C2=A7  Let=E2=80=99s move the image up in line with the text


o   In-House Teams

=C2=A7  Let=E2=80=99s move the image up in line with the text


o   Open Courses

=C2=A7  Let=E2=80=99s move the image up in line with the text, and make it =
a bit smaller



=C2=B7       The language flags

o   Add North America flags (USA/Canada) and link to current English versio=
n of the website

o   Delete =E2=80=98the=E2=80=99 in front of Netherlands

o   Have flags in alpha order
