### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by michaelrob** [MentallyFriendly/ensi#18]
**Expected Functionality**
- A user should be able to select the language they are viewing the site in 
- Once a language is selected it should remain for the duration of the session

Current confirmed languages: 
- English 
- German
- Dutch 
- Spanish
- French

Each page will need to have translated content for the above languages. An new TypeForm will need to be created for each language. 

**Additional Notes**
This can't go forward until we receive translated copy from ENSI.

**Comment by smypf** [comment]
Looking into this there are two different options that we can go with:

# Multiple sites
Each site has a different language

Benefits:
- Domains are easier to setup and point to
- Able to quickly create a new site with a new language by copying the main site.  

Cons:
- Each site will need to be updated individually
- Copying and pasting between sites does not seem to be possible. This will make the task of keeping content consistent between sites.

# Single site with multiple languages
Benefits:
- All content will be on the same page. This benefits editors as they'll be able to see the other content without having to reference two different sites.
- Switching languages will be faster

Cons:
- Domains will be harder to map to the desired language. It is still possible, but more work will be required.
- One site will have all the content for each language for it. If it's just text this isn't a big deal but if different regions have different images the page size will get large fast. This will be detrimental to the user's browsing experience.
- The site will be more complex as a result of having to add, edit and remove content.

**Comment by gillcosta** [comment]
This issue has been replaced by issue #58

**Comment by smypf** [comment]
@gillcosta I disagree with closing this issue. The language functionality is complex and needs some decisions made. I would prefer if we kept the user case in #58 but used this ticket for discussions.

Let me know if you disagree.

**Comment by smypf** [comment]
@jomentallyfriendly Can you have a look at this and let me know what you think?

**Comment by jomentallyfriendly** [comment]
Based on ENSI wanting to show that they are local they want .de to show German content and might need the site to evolve differently to all others. I currently think the multiple sites approach works better.

@vickimf since all leads are going to ENSI in Sydney we might run into a analytics disaster with this approach though. Any thoughts on this?
