### ISSUE TITLE
DES - Countries accordion

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#30]
# Use cases
- [x] Expands on click
- [x] Display practitioners located from that country
- [x] Practitioner info (photo, name, location, language spoken), LinkedIn
- [x] Practitioners are only on one country dropdown
- [x] Practitioner placeholder images

**Comment by jomentallyfriendly** [comment]
@sasha can you confirm you don't need anything from @monica-pen so the ticket can be closed?
