### ISSUE TITLE
DEV - Countries accordion

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#31]
# Use cases
- [x] Expands on click
- [x] Display practitioners located from that country
- [x] Practitioner info (photo, name, location, language spoken)
- [x] Practitioners are only on one country dropdown
- [x] ENSI should be able to add/remove countries themselves

**Comment by smypf** [comment]
@jomentallyfriendly We need clarification for this. We're not sure what the actual requirements are for this.

**Comment by jomentallyfriendly** [comment]
@smypf this is one of the areas we agreed upon last Thursday. ENSI then made changes without us and we now need to get a final decision tomorrow morning.

**Comment by smypf** [comment]
I understand. I've moved it into blocked because of that fact.

We can move it out once we've resolved the lack of understanding.

**Comment by jomentallyfriendly** [comment]
This is unblocked now as per the last meeting. @smypf

**Comment by smypf** [comment]
This has been done.
