### ISSUE TITLE
DEV - Let us help you

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#48]
# Use cases
- [x] Text
- [x] Button link to conversational flows

**Comment by jomentallyfriendly** [comment]
@smypf is there a link for this page please?

**Comment by jomentallyfriendly** [comment]
@silentparty never mind I found it http://ens-base-template.webflow.io/let-us-help-you

**Comment by jomentallyfriendly** [comment]
@smypf we need to make sure that the correct flows are linked. @vickimf can you please post the links to the final flows? 

@monica-pen did we plan to have the flows in a modal or open in a new tab?

**Comment by monica-pen** [comment]
@jomentallyfriendly @smypf Typeform displayed in a modal, similar to [Recruitment Loop](http://recruitloop.com.au/start-post). 
![conversational flow](https://cloud.githubusercontent.com/assets/15863417/20291844/45d09812-ab3d-11e6-8303-0a636aa2a669.png)

**Comment by smypf** [comment]
@jomentallyfriendly The modals are working. In mobile viewports this will open a new tab instead. This is because modals are a bad experience in mobile contexts.

I'm using the original typeforms. This can be changed easily if need be.

**Comment by jomentallyfriendly** [comment]
@smypf sweet. That's what I thought. It opens in a new tab though if I click on the buttons on chrome running fullscreen.

**Comment by smypf** [comment]
I'll check that functionality out.

**Comment by smypf** [comment]
I removed it because of #103. I'm still trying to figure out that one but this is done.
