### ISSUE TITLE
Webflow - How does content entry work for webflow? Can we have broken up text areas?

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#52]

**Comment by smypf** [comment]
Who's asking for this? What would be an example of a requirement?

**Comment by gillcosta** [comment]
@smypf This issue is a question from the roadmap, can't remember who wrote it

**Comment by smypf** [comment]
@MentallyFriendly/ensi Anyone able to answer this question?

**Comment by jomentallyfriendly** [comment]
@smypf I guess looking at the card and handwriting shows who has written it. But to solve this easily: The answer to How does content entry work in Webflow? It might related to the section on the Homepage hero where there is copy but also words changing automatically e.g. Find more 'confidence, word 2, word 3, word 4...'

**Comment by smypf** [comment]
This is fine and achievable. Nothing special required.
