### ISSUE TITLE
Webflow - Import functionality into webflow?

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#53]

**Comment by smypf** [comment]
@gillcosta wut?

**Comment by gillcosta** [comment]
@smypf It's a question from the roadmap. If it does not make sense, just close it.

**Comment by smypf** [comment]
@MentallyFriendly/ensi Anyone able to fill in what the requirements here are?

**Comment by jomentallyfriendly** [comment]
@smypf I think this relates to content entry especially to importing all translated content e.g. AU version is final. DE has been translated. Is there a way to automatically import it or does it need to be entered manually. I am not concerned about this actually.

**Comment by smypf** [comment]
No, it'll need to be added automatically.
