### ISSUE TITLE
Webflow - How does multi-language webflow functionality work?

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#54]
From Michael

**Expected Functionality**
- A user should be able to select the language they are viewing the site in 
- Once a language is selected it should remain for the duration of the session

Current confirmed languages: 
- English 
- German
- Dutch 
- Spanish
- French

Each page will need to have translated content for the above languages. An new TypeForm will need to be created for each language. 

**Additional Notes**
This can't go forward until we receive translated copy from ENSI.

**Comment by gillcosta** [comment]
From Michael


**Expected Functionality**
- A user should be able to select the language they are viewing the site in 
- Once a language is selected it should remain for the duration of the session

Current confirmed languages: 
- English 
- German
- Dutch 
- Spanish
- French

Each page will need to have translated content for the above languages. An new TypeForm will need to be created for each language. 

**Additional Notes**
This can't go forward until we receive translated copy from ENSI.

**Comment by jomentallyfriendly** [comment]
@smypf this is mainly blocked by the domain decision that is still up in the air right?

What also needs to be factored in is the Typeform & Contact Form > Zapier > Salesforce integration that will need to be redone for each language. Is that right?

**Comment by smypf** [comment]
Each form for each language will need it's own implementation.
