### ISSUE TITLE
DES - Illustrations

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#62]
# Question
- Need full list / content to inform illustrations

**Comment by monica-pen** [comment]
[ ] 6x Placeholder/photo avatar (3:2)
[ ] Amend illustrations on **homepage**
[ ] 4x Amend illustrations on **our services**
[ ] Amend illustrations on **Get in Touch banner**

**Comment by jomentallyfriendly** [comment]
@monica-pen is this ticket up to date?
