### ISSUE TITLE
Multi language support - How can we use this in conjunction with type form?

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#66]

**Comment by smypf** [comment]
We'll be using multiple different sites for this.

**Comment by gillcosta** [comment]
@smypf IF you are confident that this is the correct approach, please close this issue.

**Comment by jomentallyfriendly** [comment]
@gillcosta For each language ENS needs to copy the entire AUS site in Webflow. Forms built with Typeform need to be copied in Typeform for each language.

Integration from Typeform > Webflow and Webflow/Typeform > Zapier > Salesforce needs to be done by us for every new language.
