### ISSUE TITLE
DEV - Contact form

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#72]
# Use cases
- [x] Confirm email address before send
- [x] How did you hear about us (Full name, email, position, company, state/provence, country (dropdown), number, subject, message, how did you hear about us)
- No how can we help you

**Comment by smypf** [comment]
For the most part this has been implemented.

I need to find a way of hooking in the ability to check that the confirm email matches the email.

**Comment by smypf** [comment]
http://ens-base-template.webflow.io/contact-us

I was able to implement the usage of input patterns - http://stackoverflow.com/a/25973599/56872

**Comment by smypf** [comment]
Moving this to blocked as we don't have the designs for this page.

**Comment by jomentallyfriendly** [comment]
Double up with #109
