### ISSUE TITLE
DEV - Embed typeforms into webflow

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#77]
# Use case
- [x] Styled typeform

**Comment by smypf** [comment]
@gillcosta @monica-pen I don't think we're doing any styling for the typeform

**Comment by gillcosta** [comment]
@smypf @monica-pen Is the client expecting to be styled? Is it responsive?

**Comment by monica-pen** [comment]
@smypf @gillcosta Typeform offers limited styling (just font and colours), which I can do. Typeform is usually responsive but not sure how if it plays nice in the iFrame...

**Comment by gillcosta** [comment]
@smypf Why is this blocked? Did you work on this already? Thanks

**Comment by smypf** [comment]
I'll continue to work on this. Currently there's a bug in the implementation that needs to be resolved.

When bringing up the form a 2nd time the form will be shown twice. This is undesirable.

**Comment by smypf** [comment]
http://ens-base-template.webflow.io/let-us-help-you

**Comment by jomentallyfriendly** [comment]
@vickimf can you please post the links to the final flows?

**Comment by smypf** [comment]
@jomentallyfriendly How come this has failed?

**Comment by jomentallyfriendly** [comment]
It's related to #48 as the flows open in a new tab for me and not in a modal. Sorry should have given more detail.

**Comment by smypf** [comment]
Thx

**Comment by smypf** [comment]
#48 has been completed.
