### ISSUE TITLE
DEV - Need to build webflow homepage

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#83]

**Comment by jomentallyfriendly** [comment]
@smypf here are the words for the typewriter effect.

List of words for the typewriter effect is:
Confident
Aware
Empowered
Skillful
Connected
Successful
Astute

**Comment by smypf** [comment]
@jomentallyfriendly These words don't work for the current format (Looking for more...)

Should I change them?

Confidence
Awareness
Empowerment
Skills
Connections
Success
Astuteness

**Comment by jomentallyfriendly** [comment]
@sasha wow how could I not see this. Yeah sure use these ones instead. The others won't work.

**Comment by jomentallyfriendly** [comment]
Animation on smaller viewports has some hick-ups. @monica-pen can you please check?

Illustration seems to be too small for this viewport.
![screen shot 2016-11-15 at 2 15 25 pm](https://cloud.githubusercontent.com/assets/18299131/20291958/1b253c2a-ab3e-11e6-810e-e27eec3cc94a.png)

Illustration collides with copy in some viewport sizes.
![screen shot 2016-11-15 at 2 15 34 pm](https://cloud.githubusercontent.com/assets/18299131/20291959/1b2713b0-ab3e-11e6-997a-6e4c121fe80f.png)

There is soooo much whitespace in smaller viewports 🎱 
![screen shot 2016-11-15 at 2 15 51 pm](https://cloud.githubusercontent.com/assets/18299131/20291960/1b277c4c-ab3e-11e6-93d4-de7e9a3576b0.png)

**Comment by jomentallyfriendly** [comment]
@monica-pen can you please specify all the links for each button so they can be linked up?

**Comment by monica-pen** [comment]
@jomentallyfriendly 
All **Get in Touch** buttons go to the contact page.
All **Find out More** buttons go to the Better outcomes/Conversational Flow page.

**Comment by jomentallyfriendly** [comment]
@monica-pen cheers for that. @smypf can you please implement this?

**Comment by smypf** [comment]
@jomentallyfriendly This has been done.

**Comment by jomentallyfriendly** [comment]
Missed this one ;)

![screen shot 2016-11-16 at 2 27 19 pm](https://cloud.githubusercontent.com/assets/18299131/20333745/cf8cfc96-ac08-11e6-8453-205cbe1056f6.png)

**Comment by smypf** [comment]
Fixed thanks.
