### ISSUE TITLE
DES - Public programs

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#89]
# Use cases
- [x] Intro copy
- [x] Image / illustration
- [x] Accordion of program types

**Comment by gillcosta** [comment]
@jomentallyfriendly Do you know where the Public Programs sit? In the Our Services section? This is blocked for now.

**Comment by jomentallyfriendly** [comment]
@vickimf and I were talking about this today and currently I don't have an answer. Will work this out next week.

**Comment by monica-pen** [comment]
In the copy doc from Chris, he has relabelled 'Individual' (Skill Building) to Public Courses

https://docs.google.com/document/d/1TSCyW2zK7wC59PAxRxet1VZGGZ91BH3isabklDu62tg/edit?usp=sharing

**Comment by jomentallyfriendly** [comment]
@sasha can you confirm you don't need anything from @monica-pen so the ticket can be closed?
