### ISSUE TITLE
DES - EDM template

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#95]
# Use cases
- [ ] Header
- [ ] Text
- [ ] Image / banner
- [ ]  Footer

**Comment by jomentallyfriendly** [comment]
@monica-pen what is the status for this?

**Comment by monica-pen** [comment]
@jomentallyfriendly There's a basic design on [Invision](https://mentallyfriendly.invisionapp.com/d/main/#/console/9346707/203731577/preview) (and in the design Sketch file) with the above criteria. I've attached a PNG for reference. 
![edm](https://cloud.githubusercontent.com/assets/15863417/20286009/e7e3edea-ab18-11e6-8b17-595ebc95828f.png)
