### ISSUE TITLE
DEV - Article template

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/ensi#99]
# Use cases
- [ ] Headings 1, 2 and 3
- [ ] Block of WYSIWYG
- [ ] Rich media, images, video, audio
- [ ] mobile layout
- [ ] mobile landscape layout
- [ ] tablet layout
- [ ] desktop layout

**Comment by smypf** [comment]
This is ready to be tested: http://ens-base-template.webflow.io/our-story

**Comment by jomentallyfriendly** [comment]
QA passed.
